config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :topics do
    resources :bookmarks
end

  resources :bookmarks, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]

  end
  resources :users, only: [:new, :index, :show]

  post :incoming, to: 'incoming#create'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/how'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_presence_of :title
  validates_uniqueness_of :title

  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :topics
         has_many :bookmarks
         has_many :likes, dependent: :destroy

def liked(bookmark)
     likes.where(bookmark_id: bookmark.id).first
   end
 end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
     user = User.find(params[:sender])

     topic = Topic.find(params[:subject])

     url = params["body-plain"]

     if @user.nil?
       @user = User.new(email: user, password: "password")
       @user.save!
     end

      if @topic.nil?
        @topic = Topic.new(title: topic)
        @topic.save!
      end

      @bookmark = @topic.bookmarks.build(user: user, url: url)

      @bookmark.save!


    head 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    def index
      @topics = Topic.all
    end


    def show
      @topic = Topic.find(params[:id])

    end

    def new
      @topic = Topic.new
    end

    def edit
      @topic = Topic.find(params[:id])
    end


    def create
      @topic = Topic.new(topic_params)
      @topic.user = current_user
      if @topic.save

        flash[:notice] = "topic was saved."
        redirect_to @topic
      else

        flash.now[:alert] = "There was an error saving the topic. Please try again."
        render :new
      end
    end

    def update
      @topic = Topic.find(params[:id])
      @topic.assign_attributes(topic_params)
      if @topic.save
         flash[:notice] = "topic was updated."
         redirect_to @topic
       else
         flash.now[:alert] = "There was an error saving the topic. Please try again."
         render :edit
       end
     end

     def destroy
       @topic = Topic.find(params[:id])

       if @topic.destroy
         flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
         redirect_to topics_path
       else
         flash.now[:alert] = "There was an error deleting the topic."
         render :show
       end
     end

     private
     def topic_params
     params.require(:topic).permit(:title)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= render partial: 'likes/like', locals: { bookmark: bookmark }%>

app/views/bookmarks/_url.html.erb
<%= bookmark.url %>

app/views/bookmarks/edit.html.erb
<h1>Edit Topic</h1>
<%= link_to "Delete bookmark", @bookmark, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>

<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @bookmark] do |f| %>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "URL" %>
      </div>
        <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-8">
<%= form_for [@topic, @bookmark] do |f| %>
<div class="form-group">
  <%= f.label :url %>
  <%= f.text_field :url, class: 'form-control', placeholder: " URL title" %>
      </div>
<div class="form-group">


  <%= f.submit "Save" %>
<% end %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<%= link_to "Delete bookmark", @bookmark, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewBlocmarksProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="nav nav-tabs">
         <li><%= link_to "Blocmarks", welcome_index_path %></li>
         <li><%= link_to "About", welcome_about_path %></li>
         <li><%= link_to "Topics", topics_path %></li>
         <li><%= link_to "Your profile", users_path%></li>
       </ul>
<%= yield %>
<% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
# #2
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
<div>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-heart-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-heart"> </i>&nbsp; Like
    <% end %>
  <% end %>
</div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |form| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
      </div>
        <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%=render partial: 'form'%>

app/views/topics/index.html.erb
<h1> Topics </h1>
    <%= link_to "Create a New Topic", new_topic_path, class: 'btn btn-success' %>
    <div class="row">
  <div class="col-sm-8">
    <% @topics.each do |topic| %>
    <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to topic.title, topic %>
        <div class="bookmark">


      </h4>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-8">
<%= form_for @topic do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
      </div>
<div class="form-group">


  <%= f.submit "Save" %>
<% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1> <%= @topic.title %> </h1>
<%= link_to "Add Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
<%= link_to "Edit", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
<%= link_to "Delete", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>

  <div class="row">
  <% @topic.bookmarks.each do |bookmark| %>
  <div class="col-sm-3">
      <%= bookmark.url %>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark }%>
      <%= link_to "Delete Bookmark", bookmark, method: :delete, data: { confirm: "Are you sure you want to delete this bookmark?" } %> <br>
    </div>
    <% end %>

    </div>
    </div>

app/views/users/index.html.erb
<h1>List of current users</h1>
<h2>Your username is:</h2>
<h3>Click on your username to explore your profile</h3>

  <% @users.each do |user| %>
    <div class="media">
      <div class="media-heading">
        <%= link_to user.email, user %>
      </div>
    </div>
  <% end %>

app/views/users/show.html.erb
<h3>My Bookmarks</h3>

  <% @user_bookmarks.each do |bookmark| %>
      <div class="row">
        <div class="col-sm-8">
          <%= bookmark.url %>
          <%= link_to "Delete", bookmark, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' }  %>
        <% end %>
  </div>
</div>
    <h3>My Liked Bookmarks</h3>
      <% @liked_bookmarks.each do |like| %>
      <div class="row">
        <div class="col-md-8">
      <%= render partial: 'bookmarks/url', locals: { bookmark: like.bookmark } %>
      <%= render partial: 'likes/like', locals: { bookmark: like.bookmark } %>
      <% end %>
   </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
  <h1>Welcome to Blocmarks!</h1>